### ISSUE TITLE
为什么要加下面的代码

### ISSUE THREAD

**Issue by LVRYWIN** [Josin22/JSWave#2]
这个项目把下面两行代码注释以后就会出现偏差
CGPathAddLineToPoint(path, NULL, width, height );
CGPathAddLineToPoint(path, NULL, 0, height);
但是我想了很久都不知道为什么要加这两行代码QAQ

**Comment by Josin22** [comment]
此代码是到最右侧的path,fill整个波浪,缺了他你就看不全整个波浪
